"use client";

import Link from "next/link";
import Image from "next/image";
import { PlayCircle, Sparkles } from "lucide-react";

export default function Hero() {
  return (
    <section className="relative overflow-hidden">

      {/* Background Glow */}
      <div className="absolute left-1/2 top-20 h-[500px] w-[500px] -translate-x-1/2 rounded-full bg-green-500/20 blur-[180px]" />

      <div className="relative mx-auto flex min-h-screen max-w-7xl flex-col items-center justify-center gap-16 px-6 pt-24 lg:flex-row">

        {/* Left */}
        <div className="max-w-2xl">

          <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-green-500/30 bg-green-500/10 px-4 py-2 text-green-400">
            <Sparkles size={18} />
            AI Powered Music Discovery
          </div>

          <h1 className="text-5xl font-black leading-tight md:text-7xl">
            Music That
            <span className="block text-green-500">
              Understands
            </span>
            Your Mood.
          </h1>

          <p className="mt-8 max-w-xl text-lg leading-8 text-zinc-400">
            Tell MusicMood how you&apos;re feeling and instantly
            receive personalized playlists generated by AI.
            Discover songs that perfectly match every mood,
            moment, and activity.
          </p>

          <div className="mt-10 flex flex-wrap gap-4">

            <Link
              href="/auth"
              className="rounded-full bg-green-500 px-8 py-4 font-semibold text-black transition hover:bg-green-400"
            >
              Start Listening
            </Link>

            <button className="flex items-center gap-2 rounded-full border border-zinc-700 px-8 py-4 transition hover:border-white">
              <PlayCircle size={20} />
              Watch Demo
            </button>

          </div>

        </div>

        {/* Right */}
        <div className="relative flex w-full max-w-lg items-center justify-center">

          {/* Main Card */}
          <div className="w-full rounded-3xl border border-white/10 bg-[#181818] p-8 shadow-2xl">

            <div className="mb-6 flex items-center gap-4">

              <Image
                src="https://picsum.photos/120"
                alt="Album"
                width={96}
                height={96}
                className="h-24 w-24 rounded-xl object-cover"
              />

              <div>

                <p className="text-sm text-green-500">
                  AI Playlist
                </p>

                <h3 className="mt-2 text-2xl font-bold">
                  Late Night Coding
                </h3>

                <p className="mt-1 text-zinc-400">
                  32 Songs • 2h 18m
                </p>

              </div>

            </div>

            <div className="space-y-4">

              {[
                "Midnight City",
                "Blinding Lights",
                "Holocene",
                "Sunset Lover",
              ].map((song) => (
                <div
                  key={song}
                  className="flex items-center justify-between rounded-lg bg-zinc-900 p-3"
                >
                  <span>{song}</span>

                  <PlayCircle
                    className="text-green-500"
                    size={20}
                  />
                </div>
              ))}

            </div>

          </div>

          {/* Floating Cards */}
          <div className="absolute -left-10 top-10 hidden rounded-xl bg-zinc-900 p-4 shadow-xl lg:block">
            🎧 Chill Vibes
          </div>

          <div className="absolute -right-8 bottom-10 hidden rounded-xl bg-zinc-900 p-4 shadow-xl lg:block">
            🌙 Focus Mix
          </div>

        </div>

      </div>

    </section>
  );
}